### ISSUE TITLE
Organizar repositório

### ISSUE THREAD

**Issue by ElidiaVidal** [redelivre/MutiraoUX#1]
- [x] A. Organização e sistematização no github.com das demandas dos softwares a partir de
relacionamento com usuários e comunidades de desenvolvimento.

- [x] B. Estudo e modelagem com foco na experiência do usuário para potencializar a replicabilidade dos
Softwares;

- [x] C. Produção de conteúdos explicativos sobre os softwares para usuários finais, orientando
designers para produção de peças gráficas e digitais e programadores para produção de
websites de portfólio;

- [x] D. Curadoria de Maratona Hacker para desenvolvimento das soluções apresentadas (a serem
definidas pela coordenação).

**Comment by uira** [comment]
Sugiro que cada um desses itens vire um milestone para que seja distribuídas as tarefas(issues) necessárias para a execução de cada produto.

**Comment by uira** [comment]
Criados os Milestones (https://github.com/redelivre/MutiraoUX/milestones)
