### ISSUE TITLE
Curadoria de Experiências na América Latina

### ISSUE THREAD

**Issue by uira** [redelivre/MutiraoUX#10]
- [x] Claudio Prado - Maricá

**Comment by ElidiaVidal** [comment]
Doc com nomes e mini bios: http://bit.ly/CuradoriaExperienciasAL

**Comment by Andreqlp** [comment]
@ElidiaVidal juntar com o @uira para completar a lista de contatos e mini-bios,

**Comment by Andreqlp** [comment]
Lista finalizada e evento realizado.
