### ISSUE TITLE
Criar relatório da organização das demandas.

### ISSUE THREAD

**Issue by uira** [redelivre/MutiraoUX#12]
https://docs.google.com/document/d/1NDBrt54Ore-GGTY8mCv6hKdcEQWWHzdkYIGIryYk8R4/edit#

**Comment by Andreqlp** [comment]
[Relatório dos Produtos A e B](https://docs.google.com/document/d/1NDBrt54Ore-GGTY8mCv6hKdcEQWWHzdkYIGIryYk8R4)
[Relatório dos Produtos C e D](https://docs.google.com/document/d/1qTTvwYEF71HN_gJDjoGvpTTVPc7PBtd1wn9FpTPq1S4)
