### ISSUE TITLE
Implementar Tabela "Best Practices of Free Software Projects"

### ISSUE THREAD

**Issue by uira** [redelivre/MutiraoUX#13]
A idéia é usar a tabela de "Best Practices of Free Software Projects", que dá pontos pros diversos princípios que devem ser seguidos por um projeto livre, para que sejam utilizáveis por outras pessoas e coletivos.  ![captura de tela 2017-04-06 as 12 07 15](https://cloud.githubusercontent.com/assets/89998/24761412/a0dbd534-1ac1-11e7-9fdd-4bd03991b1f7.png)  Então, a idéia é verificar como cada Ferramenta está - ou não, atendendo à esses princípios.

**Comment by Andreqlp** [comment]
Planilha para preenchimento: https://docs.google.com/spreadsheets/d/1dTT91ktpE5FNwvUTl0SjnSnFa0w_EgKxV7mc44hTE0Q/edit#gid=149271928

**Comment by Andreqlp** [comment]
Tabela preenchida.
