### ISSUE TITLE
Teste: [CNPC] Conjunto de funcionalidades a serem implementadas na plataforma

### ISSUE THREAD

**Issue by ElidiaVidal** [redelivre/MutiraoUX#14]
- [ ] Anexar documentos relevantes
- [ ] Inserir nos comentários: vídeos, fotos e áudios
- [ ] Citar outro participante da plataforma
- [ ] Propor mesclar propostas e conteúdos
- [ ] Filtrar conteúdos relacionados em todos os debates da plataforma e por usuário
- [ ] Extrair relatórios por pauta, temática, palavra-chave, usuário;
- [ ] Buscar conteúdos por sua cronologia
- [ ] Busca por comentários de usuários

**Comment by Andreqlp** [comment]
verificar andamento pelo repositório do CNPC : https://github.com/redelivre/novo-cnpc
