### ISSUE TITLE
Verificar  [Toolkit de Ferramentas de Consulta Pública]

### ISSUE THREAD

**Issue by ElidiaVidal** [redelivre/MutiraoUX#17]
- [ ] Módulo de comentários por parágrafo;
- [ ] Integração do sistema de relatórios desenvolvido para consulta dos Direitos Autorais;
- [ ] Implementação do sistema de votação Pair Wise

**Comment by ElidiaVidal** [comment]
Toolkit em processo de desenvolvimento - a ser entregue junto aos itens C e D do edital, no segundo relatório.

**Comment by Andreqlp** [comment]
## Toolkit de Consultas Públicas
Página criada: http://labculturadigital.redelivre.org.br/suite-toolkit
O Toolkit de Consultas Públicas utiliza o plugin para WordPress "Delibera" que possibilita a gestão de processos participativos em Conselhos de Políticas Públicas, conferências, consultas públicas, ou outros processos participativos para a democracia online. O plugin foi desenvolvido com o objetivo de permitir o diálogo, interação, troca de conteúdo, a busca por consensos e a tomada de decisões por meio de tecnologias digitais. De forma a potencializar o ambiente virtual para a transformação do mundo real. Suas etapas de funcionamento são modulares, permitindo a criação e validação de pautas; discussão das pautas e apresentação das propostas de encaminhamento; sistematização dos encaminhamentos; e votação dos encaminhamentos.

**O que o laboratório fez:**
- Sistema de Votação;
- Implementação de modelos de votação de comparação entre  pares (PairWise), escolha simples e múltipla escolha;
- Módulo de Comentários por parágrafo;
- Validação de Documentos;
- Tema WordPress para consultas;

**Manual de Uso:** http://escoladedebate.cnpc.cultura.gov.br 
**Link para o produto:**  http://delibera.redelivre.org.br 
**Repositório:** https://github.com/culturagovbr/delibera  
**Licença:** https://creativecommons.org/licenses/by-sa/4.0
