### ISSUE TITLE
Edital de Fomento à Colaboração

### ISSUE THREAD

**Issue by uira** [redelivre/MutiraoUX#19]
- [ ] Fechar minuta do edital: https://docs.google.com/document/d/19dJwlvSItXMWHqGL-9RY4tpaPbfki5U2FQwlYJGhCfg/edit
- [ ] Fechar Milestones de Desenvolvimento e Documentação nos respectivos repositórios de cada projeto
- [ ] Fazer reunião para validar viabilidade com @jacsonp e @cabelotaina

**Comment by Andreqlp** [comment]
o edital não foi lançado durante o período da consultoria
