### ISSUE TITLE
Mapeamento dos canais de comunicação com os usuários e comunidades de desenvolvimento

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/MutiraoUX#2]
- [X] Repositórios
- [X] Grupos no telegram e whatsapp
- [x] Sites
- [ ] Aplicativos
- [X] E-mails e serviços de suporte

**Comment by Andreqlp** [comment]
Ver documentos do plano de trabalho ( https://drive.google.com/drive/u/1/folders/0BwTCAeg_ZAeBSjIyMHAyTUtMV0E ) , com o detalhamento dos produtos. Esses detalhamentos já são issues.

**Comment by ElidiaVidal** [comment]
Repositórios:
Wordpress https://github.com/redelivre/redelivre/issues 
Jaiminho https://github.com/redelivre/jaiminho/issues 
Delibera https://github.com/redelivre/novo-cnpc/issues 

Telegram:
Grupo: Lab Cult Tec; Retaguarda

**Comment by jacsonp** [comment]
Delibera  https://github.com/redelivre/delibera/issues
Customização para o CNPC do DIVI e do Delibera: https://github.com/redelivre/novo-cnpc/issues

**Comment by Andreqlp** [comment]
## Delibera:
[Site do Delibera](http://delibera.redelivre.org.br/)
[Site CNPC](http://cnpc.cultura.gov.br/)
[Site da Escola de Debate](http://escoladedebate.cnpc.cultura.gov.br/) 
[Canal do Laboratório de Cultura Digital no Youtube](https://www.youtube.com/channel/UCHxtG0O795Ens_Aq3rtTR6Q) (95 inscritos)
[Canal do Lab de Cultura Digital](https://www.youtube.com/channel/UCdVZJbuA53tA7H3LbgBtiSw) (19 inscritos, 8 vídeos incluindo o stop motion do delibera)
[Página do Face no Laboratório de Cultura Digital](https://www.facebook.com/LabCulturaDigital?fref=ts) (3.456 curtidas)
[Citação no site Cultura Digital Br](http://culturadigital.br/plataformascolaborativas/delibera-democracia-digital/) (lá tem instruções e guias em vídeo de como instalar e usar o Delibera)
