### ISSUE TITLE
Lista de conteúdos explicativos sobre os softwares

### ISSUE THREAD

**Issue by ElidiaVidal** [redelivre/MutiraoUX#20]

**Comment by ElidiaVidal** [comment]
# Wordpress:

- [x] 1) Como criar um site em 10 passos simples (1- Cadastro; 2- Escolha o seu tema; 3- Defina o conteúdo e funcionalidades da coluna lateral do seu site; 4- Organize o menu com as informações da sua campanha; 5- Edite as opções do seu tema; 6- Configurar cabeçalho; 7- Se desejar, deixe o fundo do seu site com a sua cara; 8- Editar as páginas existentes; 9- Criar novas páginas; 10- Excluir páginas que você não vai usar);

- [x] 2) 3 dicas para melhorar a performance do seu site: template, plugins e tipos de mídia;

- [ ] 3) Para que serve a criação de evento;

- [x] 4) Como criar um novo post (formatação, inserção de mídias, imagem destacada, categoria e Tags);

- [x] 5) Como publicar e agendar um novo post (no agendamento ver questão do hr da plataforma);

- [ ] 6) Como editar o horário do Wordpress na sua conta;

- [ ] 7) Como gerenciar os comentários do seu site;

- [ ] 8) Para que serve a “mobilização” e o que você deve fazer (banner, foto, redes sociais, “enviar para um amigo”);

- [ ] 9) Para o que serve “Item no Mapa” e como adicionar (categorias, configurações, aparência, marcadores);

- [x] 10) Como criar um novo projeto com a mesma conta.

**Comment by ElidiaVidal** [comment]
# Jaiminho:

- [x] 1) Como utilizar o serviço de disparo de e-mails Jaiminho em 5 passos (1 - Cadastro; 2 - Configurações Remetente; 3 - Configurações lista de e-mails; 4 - Escolher Modelo; 5 - Disparo teste e disparo);

- [x] 2) Os modelos disponíveis para disparos. Formatos ideais para diferentes tipos de e-mails;

- [ ] 3) Como obter relatórios do disparo de e-mails e para que serve;

- [ ] 4) Como exportar as listas de e-mails cadastradas e remover e-mails inexistentes;

- [ ] 5) Melhore o desempenho com as configurações avançadas;

- [x] 6) Como importar uma lista (arquivo) no Jaiminho.

**Comment by uira** [comment]
@ElidiaVidal Então, acho que é bem isso. E minha sugestão é a gente criar uma tag de "documentação", lá no repositório do Jaiminho, e criar uma issue pra cada um dos conteúdos. Que acham?

**Comment by ElidiaVidal** [comment]
Essa tag de documentação seria sinônimo de registro, certo? Já existe uma tag com esse nome, acho que podemos criar uma com outro nome, tipo "tutorial" ou algo similar. O que acham?
Acho massa deixar registrado no repositório do Jaiminho.

**Comment by ElidiaVidal** [comment]
# Delibera/CNPC: 
 
- [ ] 1) Como criar seu site na plataforma Delibera e promover participação; 
 
- [ ] 2) Como propor pautas na plataforma (cadastro no ID cultura, login, propor pautas) e para que serve; 
 
- [ ] 3) Como debater no Delibera/CNPC (validação, discussão, relatoria, votação e resolução de pauta); 
 
- [ ] 4) Como escrever posts e criar eventos na agenda e para que serve; 
 
- [ ] 5) Como configurar uma pauta, gerenciar categorias, atualizar textos e documentos, publicar conteúdos e produzir relatórios, e em quais circunstâncias você deve fazer isso; 
 
- [ ] 6) Como usar a plataforma/ fluxos de interatividade  
_(citar exemplos)_; 
 
- [ ] 7)  O que deve ser feito para acompanhar e fiscalizar a execução do Plano Nacional de Cultura; 
 
- [ ] 8) Como participar do estabelecimento das diretrizes gerais para aplicação dos recursos do Fundo Nacional de Cultura e participar da aprovação do regimento interno da Conferência Nacional de Cultura; 
 
- [ ] 9) O que você encontra do site Delibera/CNPC, o que pode ser feito e a quais públicos se destina; 
 
- [ ] 10) Diferenças entre as funções e demandas dos “colegiados setoriais”, “plenários e gt’s” e “comissões” no site Delibera/CNPC.

**Comment by Andreqlp** [comment]
@ElidiaVidal pensar na adequação das pautas para criação de uma documentação genérica para o Delibera. Uma sugestão seria pensar em pequenos passos de integração do presencial para o virtual, tipo como definir uma pauta. Outra sugestão seria ver com o Jean sobre como o delibera poderia ajudá-lo na organização dos fóruns.

Vou marcar com o João para apresentarmos esses pontos junto com a proposta da pesquisa.

**Comment by ElidiaVidal** [comment]
Editei acima @Andreqlp

**Comment by ElidiaVidal** [comment]
# Delibera:

- [ ] 1) Como criar seu site na plataforma Delibera e promover participação (instalação e configuração);

- [ ] 2) Como escolher a interface do seu site Delibera

- [ ] 3) As 4 etapas de funcionamento do Delibera: criação e validação de pautas; discussão das pautas e apresentação das propostas de encaminhamento; sistematização dos encaminhamentos e votação dos encaminhamentos;

- [ ] 4) Apresentação Delibera: interação, troca de conteúdo e tomada de decisões;

- [ ] 5) As duas maneiras de se criar uma pauta no Delibera;

- [ ] 6) O fluxo de vida de uma pauta no Delibera.

**Comment by Andreqlp** [comment]
Hangout 6/6/17
- Jackson está fazendo uma limpa no site do WP e do CNPC (deve ficar pronto até o final da semana).
- Pensar no Delibera de forma ampla.

- [ ] Fazer nessa semana os primeiros vídeos do Jaiminho.
- [ ] Conversar com o Whashington sobre a proposta do tema do Delibera e dar um feedback sobre a proposta do Jackson.

**Comment by Andreqlp** [comment]
#21

**Comment by Andreqlp** [comment]
Exemplos de Roteiro_Tutoriais para o Wordpress Multisites https://docs.google.com/document/d/1bChVyHJXuOwRlwY1ThkRhOcJ4gkU1laQg3ThA-J-8sI/edit

- Como criar um site em 5 passos simples
- 3 dicas para melhorar a performance do seu site: template, plugins e tipos de mídia
- Como criar um novo post (formatação, inserção de mídias, imagem destacada, categoria e Tags)
