### ISSUE TITLE
Sistematizar as demandas

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/MutiraoUX#3]
- [x]  Levantamento das demandas
- [x] Checar as demandas mais recorrentes
- [x] Categorizar e encaminhar

**Comment by Andreqlp** [comment]
Proposta de sistematização a partir de tags:
https://docs.google.com/document/d/1DHHk2n4X5OM7mvQvlE_kZxdf5VHje4Ps-DSUIxD7hdE/edit?usp=sharing

**Comment by uira** [comment]
Aprovada e implementada.

**Comment by Andreqlp** [comment]
A proposta de tagueamento virou uma wiki no repositório principal da Rede Livre:
https://github.com/redelivre/redelivre/wiki/Tagueamento-das-issues
