### ISSUE TITLE
Levantar informações sobre Rede Livre e seus parceiros

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/MutiraoUX#4]
Levantar projetos, inciativas, produtos

**Comment by Andreqlp** [comment]
Informações disponíveis na pasta TEC do LAB: https://drive.google.com/drive/folders/0BwTCAeg_ZAeBVV9VLW9zejNUeXM

**Comment by Andreqlp** [comment]
blog/forúm de discussão para tratar do desenvolvimento da própria rede: http://dev.redelivre.org.br/

**Comment by uira** [comment]
@Andreqlp podia ver com o @jacsonp e o @jpmehl qual o plano, abandonar ou se a gente retoma esse cara.

**Comment by Andreqlp** [comment]
essa foi uma demanda nossa para o início do projeto, que acabou se resolvendo  quando fomos experimentando os serviços. Temos agora  a demanda do contato dos usuários da rede livre que está na issue da .pesquisa #11
