### ISSUE TITLE
Testar os produtos da Rede Livre

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/MutiraoUX#5]
- [x] Plataforma Delibera/CNPC
- [x] Sistema de envio de e-mails (Jaiminho)
- [x] Plataforma WordPress
- [ ] Toolkit para consultas públicas
- [x] Aplicativo mobile da plataforma Delibera.

**Comment by uira** [comment]
Usar essa tabela como referência, talvez ela pudesse ser uma página padrão de Especificações Técnicas de cada ferramenta:

https://docs.google.com/document/d/1bmi-kI6m8sigtlWBur7pxadAZw1JNntPqZtFWlxkQm4/edit#bookmark=id.7izzhhanaps2

**Comment by Andreqlp** [comment]
Imagino que a tua ideia @uira  seja criar uma tabela resumo com a quantidade de issues de cada produto e classificadas por algumas variáveis como as da tags (status, tipo, área, prioridade e complexidade).
Tipo assim: https://docs.google.com/spreadsheets/d/1dTT91ktpE5FNwvUTl0SjnSnFa0w_EgKxV7mc44hTE0Q/edit#gid=0

**Comment by uira** [comment]
Não, @Andreqlp , a idéia é usar a tabela de "Best Practices of Free Software Projects", que dá pontos pros diversos princípios que devem ser seguidos por um projeto livre, para que sejam utilizáveis por outras pessoas e coletivos.

![captura de tela 2017-04-06 as 12 07 15](https://cloud.githubusercontent.com/assets/89998/24761412/a0dbd534-1ac1-11e7-9fdd-4bd03991b1f7.png)

Então, a idéia é verificar como cada Ferramenta está - ou não, atendendo à esses princípios.

**Comment by Andreqlp** [comment]
Toolkit para consultas públicas; (o Toolkit ainda não foi desenvolvido. Por isso, os itens A e B relativos às disposições preliminares dos “Produtos a serem entregues”, item 2.2.3.1, do edital será entregue junto ao relatório do próximo produto a ser entregue.)
