### ISSUE TITLE
Mapear e Atualizar Issues em relação ao novo Plano de Trabalho do LabCD

### ISSUE THREAD

**Issue by uira** [redelivre/MutiraoUX#7]
Link para o Novo Plano de Trabalho:
https://drive.google.com/open?id=0BwTCAeg_ZAeBdmZrQWNMZHdGQWc

**Comment by uira** [comment]
@Andreqlp e @ElidiaVidal, vcs fizeram isso aqui no processo de identificação das issues?

![captura de tela 2017-04-07 as 02 04 11](https://cloud.githubusercontent.com/assets/89998/24786338/0dd4ea52-1b37-11e7-9c4e-cf42e51f8554.png)
![captura de tela 2017-04-07 as 02 05 32](https://cloud.githubusercontent.com/assets/89998/24786339/0dd7c862-1b37-11e7-9fa5-44e7069d517f.png)
![captura de tela 2017-04-07 as 02 06 07](https://cloud.githubusercontent.com/assets/89998/24786340/0dda783c-1b37-11e7-9eb3-3abfee6defc3.png)

**Comment by Andreqlp** [comment]
Consideramos a experiência do usuário na utilização dos softwares e o andamento das issues já existentes nos repositórios que contemplavam as demandas do novo plano de trabalho.
