### ISSUE TITLE
Testar e Atualizar conteúdo da Escola de Debates

### ISSUE THREAD

**Issue by uira** [redelivre/MutiraoUX#8]
Referência:
http://escoladedebate.cnpc.cultura.gov.br/

A proposta é atualizar esse ambiente e agregar as informações de cada ferramenta.

**Comment by Andreqlp** [comment]
@ElidiaVidal fazer um pequeno relato do site da escola de debates sobre o que precisa mudar e o que pode melhorar. Também aproveitar e já pensar nos vídeos (os tipos de vídeo e o que precisa ser abordado em cada um) que serão gravados pensando no público final.

**Comment by Andreqlp** [comment]
Vamos gerar conteúdo para o Delibera e parte desse conteúdo poderá ser aproveitado para a escola de debates.
